### ISSUE TITLE
Update to API 1.5.5 and update way of the PoST setup

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1062]
### Rationale
Right now in the [0.2.10 version](https://github.com/spacemeshos/smapp/pull/1040), we are using [1.5.3](https://github.com/spacemeshos/api/compare/v1.5.0...v1.5.3)  version of [API](https://github.com/spacemeshos/api) , and we need to migrate to [1.5.5](https://github.com/spacemeshos/api/compare/v1.5.3...v1.5.5) 

### Prerequisites

instead of asking a user how many files their post shall be split, the user needs to be asked how large their PoST files shall be at max before they are split

a reasonable default value is maybe 2 GiB (?), since this works on all file systems, bigger files can cause issues with older filesystems like FAT32 (old windows) or ext2 (old Linux systems)

also when communicating this to a user it might make sense to give them the hint, that larger files have the advantage of being more efficient at generating / reading them while smaller files require less time to re-initalize should one of the files get corrupted due to a filesystem error or disk failure

### TODO User story

Describe the most straightforward usage scenario

- [ ] I open this
- [ ] I create that
- [ ] I click there
- [ ] I benefit from the result in a such way

### TODO Acceptance criteria

Provide some steps that an end-user would be able to perform when the feature could be considered as implemented. E.g.:

- [ ] The basic scenario works as described
- [ ] If I do not enter a value, an error¹ is shown
- [ ] Clicking OK changes all nodes’ labels to the Foo value
