### ISSUE TITLE
User Feedback add username/email for the feedback title and get rid of stack trace 

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1471]
## Rationale

1. We need to search for user feedback using either the discord handle or user email, not just the issue ID.

2. Additionally, we need to remove the stack trace from user feedback events. We have been automatically attaching the stack trace to user feedback events as a workaround to make Sentry accept user feedback.

3. Include the `go-spacemesh` node version as a property for the Sentry event. This will provide information not only about the `SMApp` version but also about the `go-spacemesh` node version.

4. For larger payloads, there seems to be a formatting issue. You can check out this [example link](https://spacemesh.sentry.io/issues/4451758277/?alert_rule_id=11649342&alert_type=issue&project=6324919&referrer=slack) for reference.
 

## User Story

- [ ] Open `SMApp`.
- [ ] Click "Report an issue!"
- [ ] Fill out the form and click "Report."
- [ ] Go to Sentry and find the issue by discord handle, user email, or issue ID.

## Acceptance Criteria

- [ ] It is possible to find the issue by discord handle.
- [ ] It is possible to find the issue by email.
- [ ] It is possible to find the issue by issue ID.
- [ ] The event includes the node version, similar to the app version.
- [ ] Formating present for large payloads

## Implementation Steps

1. To add a user name and email, we need to attach form input to the message.

2. To clean up the call stack, refer to the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) and apply the changes in Sentry.

3. To add the `go-spacemesh` node version to attributes, use the guidance provided in the [documentation](https://docs.sentry.io/platforms/javascript/enriching-events/context/).

## Testing Procedure

1. Open the `SMApp`.
2. Click on the "Report an issue!" option.
3. Fill out the issue reporting form.
4. Click the "Report" button to submit the issue.
5. Open Sentry.
6. **Test 1:**
   - Use the discord handle of the account that reported the issue to search for it.
   - Verify that the issue related to the provided discord handle is displayed.
7. **Test 2:**
   - Use the user email of the account that reported the issue to search for it.
   - Verify that the issue related to the provided email is displayed.
8. **Test 3:**
   - Use the issue ID to search for a specific issue.
   - Verify that the issue with the provided ID is displayed.
9. **Test 4:**
   - Ensure that all events include the node version information.
10. **Test 5:**
    - Verify the formatting and display of larger payloads by checking the payload in the Sentry.

**Comment by brusherru** [comment]
Username = discord handle ;)
