### ISSUE TITLE
UI review tracking issue (version 0.0.1 - initial distro)

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#174]
- [x] Font issue - see shared screen shots - some texts appear with a serif system font. Also main menu font seems wrong and different than the one in dev builds
- [x] Replace 'passphrase' with 'password' in all screens. Most screen say password, passphrase appears in other. e.g. text input boxes in the create wallet screen. Settings screen says passphrase - need to say password.
- [x] Unify sentences casing in all screens. Uppercase all sentences - some start with lower-case letter. Most start with uppercase. For example in the Select Drive screen - 'select the hard-drive...' should be 'Select the hard-drive'...
- [x] Unify casing of large buttons text. e.g. Always UPPER case all text or only upper-case first letter. For example, restore wallet screen - purple buttons text is only first letter upper cased but other buttons such as NEXT, RSTORE are all upper. Another example - Unlock button copy in the unlock screen - needs to be UNLOCK and not Unlock...
- [x] Select drive screen. When only 1 drive is listed, select it to save 1-click from the user so he just needs to click next. This will be a very common case
- [x] Add hover tooltip to main menu commands (mining, wallet, contacts)
- [x] Allocate space screen. remove 'HARD DRIVE' from the green text so only the drive name is green. It is a bit odd right now. On my mbp it reads in green 'Macintosh HD HARD DRIVE'. Should be 'Macintosh HD' which is my drive name
- [x] Change the quit app dialog. Copy: 'Quit Spacemesh and stop the miner?' default button: "Keep running in background", other button: "Quit". Only display this confirmation dialog if the miner is running. If it is not running then just quit when the user asked to quit. When user switched the app to background show a notification about the miner still running in the background. 
- [x] Quit warning - we must add description regarding what quitting means. We need to communicate to users that quitting stops the node (if it is running) and user may miss some mining awards. So, we need to make this dialog box more robust with a place for an explanation of these things to the users. Currently, no motivation for running in the background is provided so many users are just likely to quit. I will provide a sketch mock for how this may be implemented.
- [x] Spacemesh Miner screen. We need to add a bullet entry about firewall / network configuration to make the node routable which is critical. Copy: "Important: configure your network to accept incoming app connections. [Learn more...]". With a link to a page in the guide about this.
- [x] Discussion: Contacts is a main feature in the menu. If it stays then remove 'my contacts' command from all transactions screen. If it goes then contacts can be accessible from settings and from the txs screen. Regardless, contacts button text should be consistent - the feature is either contacts or my contacts
- [x] Wallet screen - move copy button to the right of the address - it is oddly placed. It should . have a hover and click state and a tooltip stating 'copied' should be displayed on click.
- [x] Wallet screen - black arrows in send and request buttons are odd. Discussion: change them to white like the text
- [x] Transactions log screen - missing guide blue link at bottom left of screen to help screen on this feature
- [x] Missing global status message area. When user logs-out via the log-out button we should display 'You are logged out from your wallet'.
- [x] Unlock screen - add sentence above the text box: 'Please enter your wallet password'.
- [x] Add remove all data to the settings so the app can be tested from virgin / fresh state w/o reinstalling it. Very useful for testing.
- [x] Add privacy and terms of service to pages on the testnet guide and link to them from the settings screen
- [x] Rename the App from 'Spacemesh Wallet' to 'Spacemesh'
- [x] Settings screen - auto start section: add sentence. It is not clear. Change to a more descriptive: 'Auto start Spacemesh when your computer starts: [ON/ OFF]
- [x] Settings screen - can't change password. Getting a transparent loader than never goes away
- [x] In wallet password protected, click 'show me where it is'. Result: config.json is selected in the data folder. Expected: the wallet data file should be selected. Also change copy of 'show me where it is' to 'Show wallet file'.
- [x] Contacts feature: remove email field from contacts. A contact is a friendly nickname + address. Maybe we'll add more fields later but email doesn't add much value right now.
- [x] Restore from file screen copy changes: 'A restore file has been downloaded to your computer' -.> 'A wallet restore file has been saved.'. 'You can use this file to restore your spacemesh wallet in another location.' -> 'You can use this file to restore your spacemesh wallet on any computer'. 'Show me where it is' -> 'Browse file location'.
- [x] Restore wallet screen copy changes. 'Locate your existing wallet file' -> 'Locate a wallet restore file'. 'drag & drop or browse for another file' -> 'Drop a wallet restore file here or [locate a restore file]
- [x] Clicking on 'PRINT' in the 12 words backup screen doesn't do anything. Expected: open the OS print dialog to print the words. 
- [x] 12 words backup restore - it will be nice to be able to drag words from position 1 - 12 in the case user dropped them at the wrong spot - it happens quite often. User should need to start all over again if he dragged the 4th word to a different slot by accident. We should be more forgiving in this case and save the user some work. 
- [x] Implement offline banner and prevent all actions calling for node during offline mode

@IlyaVi @yhaspel

**Comment by avive** [comment]
Added a few more small tasks to the list
