### ISSUE TITLE
UI Review 2.0 Master Issue for tracking

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#204]
- [x] Wallet screen - display actual wallet name in wallet instead of 'WALLET'
- [x] Disable storage options in miner setup beyond the available free space
- [x] Show quit warning dialog box before quitting the app - currently it just quits even if the miner is running
- [x] New account help copy. Change 'Created account is ready for use immediately'. to 'New accounts will be added to [current_wallet_name_in_purple_or_green_color].
- [x] Global change: Always add `0x` when displaying an address - long or short form e.g. `0x1234...1234` or `0x12fac012....`
- [x] `Setup will use the GPU and may take up to 48 hours` -> `Setup will use your GPU and may take up to 48 hours`
- [x] Move 'delete all' command to advanced settings. Change label to 'Reinstall App' from 'Delete all wallets and settings'. Change button label to 'Reinstall' from 'DELETE ALL'. Change warning label copy to: 'WARNING: All wallets, addresses and settings will be lost. Are you sure you want to do this?'
- [x] Wallet screen - create new contact purple area: the buttons colors over the purple are not good - maybe change `cancel` to light grey and `create` to white. It is very hard to read them and blue or gray over purple just don't work well together.
- [x] Create contact purple area in wallet screen: can't paste an address after inputing an invalid address. Expected on first use to be able to edit the address in the purple area.
- [x] After creating a contact, and clicking inside the 'Send to' text box I expected to see a drop-down to allow me to select the contact by name - I don't see it - can't send to an existing contact... There should be an arrow down drop-down even w/o the user typing anything into this box. it caught me by surprise that it is only displayed when I enter a letter into the box.
- [x] Send SMC note filed - can't enter any spaces! expected to be able to enter a note such as `Buying 3 unicorns` into this free text field.
- [x] First time user experience - welcome screen - is it step 1? There are no steps indicators on the left. After it, the flow moves to step number 2 for the next screen... Possible fixes: make 'protect your wallet' screen step 1 and remove the invisible/silent `setup wallet+miner` step.
- [x] Legal section in settings. Change section name to 'Legal'. Change copy to: `Read our terms of service, disclaimer or privacy statement` - with each document a blue link to the applicable page in the guide.
- [x] short form address format: `0x1234...1234` - leading 0x, 4 hex chars, 3 dots, 4 hex chars. This should be displayed everywhere in a consistent manner. e.g. right now, in the send smc screen we have this format: `ebee4e63a6b0....69b8b4ee0443`...
- [x] request smc screen - last bullet copy: `You can mine Spacemesh Coins (SMC) by setting up mining`
- [x] Copied address to clipboard should include the leading `0x` prefix. It currently does not.
- [x] Welcome screen. Restore button copy should be 'RESTORE WALLET'.
- [x] Welcome screen help copy for light version should be: 'SET UP ONLY A WALLET, YOU CAN SET UP MINING LATER'
- [x] Settings screen - restore wallet copy: change `Restore wallet from file or mnemonic phrase` to `Restore wallet from backup file or a 12 words list`
- [x] Restore from backup screen copy:  `or locate a restore file` to `or locate a wallet backup file`. Also - or should not be part of the link, link should start with `a...`
