### ISSUE TITLE
Multiple Wallets Support

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#580]
### Rationale
Right now Smapp allows users to create or restore a single wallet file and then work only with it.
We want to allow users to have more than one wallet and switch easily between them. Including ledger wallets.
This issue also requires fixing the bug, that the user can not create (or restore another) wallet file when he already has one.

### Tasks
_Might be decomposed into smaller issues._
- [x] allow the user to create a new wallet file when he already has one
- [x] allow the user to restore a wallet when he already has one
- [x] allow the user to store wallet files anywhere on the filesystem and just remember paths to wallet files (only for "recover from file" flow)
- [x] allow the user to select the wallet to open on Smapp startup (2nd+ app sessions)
        I have an idea just to show up a block next to the main one with a list of available wallets. So it will be easier to select one. Also, Smapp can remember which one was opened last time and auto-select it on the next app session.
- [x] allow the user to switch between wallets when he already unlocked one (E.G. via Settings screen)
        It might be just a button on the Settings screen under the Wallet section. When the user clicks on this button it opens the unlock wallet screen, which has a list of available wallets and buttons to create a new wallet or restore another one.

**Comment by avive** [comment]
@brusherru - how are we on these requirements in release 0.2.3?

**Comment by brusherru** [comment]
Release 0.2.3 does not include this feature.
Working on it include it in the next release.

**Comment by brusherru** [comment]
@avive everything is almost done except one things: wallets still created at the same place and User can't choose to create it in another place.

Also unlock screen looks like this now:
<img width="1392" alt="Screenshot 2022-03-31 at 02 08 50" src="https://user-images.githubusercontent.com/1897530/160912090-3f97bc80-4e03-49bf-98ec-b42d0502c9a7.png">

But I need to clarify a couple of nuances:
1. When User decided to close the wallet (to choose another one, or even leave Smapp with unlocked wallet) — should I stop the node? Or keep it working? In case if he want to keep smeshing it sounds that it is better to keep it working.
2. When User created wallet A and setted up smeshing (so rewards will come to account from wallet A), and then he created wallet B and switched to it — should it keep smeshing for account in wallet A?

**Comment by brusherru** [comment]
Also, I think that it is better to ask User to set the name of the wallet in creation wallet flow, with the default "Main wallet".
In this case it will be easier to have a meaningful names in the dropdown when User creates some wallets (otherwise there will be few "Main wallet"s).

I think we can do it within one step, which will ask to choose the directory to store the wallet file and set the name. For the directory it also can have a default, the same as we have now.

And since wallet files can be placed in different places in FS, I think that we need to introduce a checkbox in "recover from file" flow, to allow user to choose copy wallet file or not.

In addition, and just to not forget about it, all the new stuff in a wallet creation flow (like directory and wallet name) should also exist in the "recover from mnemonics" flow.

**Comment by avive** [comment]
Good questions - regarding the first 2:
0. Only display the drop-down is Smapp is aware of more than 1 wallet. 80% of the users will use only 1.
1. When user closes a wallet and local node is running then node should not be shut down. However, remember we talked about each wallet having meta-data of the net-id it was last used with? So if user opens a new wallet with the same netId then node can keep being open (even if wallet was used on same netId but in wallet-only mode) last session. If a wallet is opened with a different netId to local node then user should be prompted about it and have the option to use this wallet with current netId. If he decides to migrate wallet to this netId then it should be opened with the current local node if it was running, if it was not - open against public api for this netID - we need to flow chart all of these - there are few more cases to consider but that's the main concept.
2. Smapp should never change the smesher rewards address w/o explicit user action. He should be able to go to settings and set any of wallet B address as rewards address - in this case - it should change.

**Comment by avive** [comment]
> Also, I think that it is better to ask User to set the name of the wallet in creation wallet flow, with the default "Main wallet".
In this case it will be easier to have a meaningful names in the dropdown when User creates some wallets (otherwise there will be few "Main wallet"s).

I think that we should prompt for wallet-name as part of wallet creation flow only on the 2nd time user creates a wallet to make the basic use-case simple and short. We should not suggest 'main wallet' as the default name for 2nd or later wallet, user will need to name it. So, when there's a drop-down (only 2 or more wallets) they will have distinctive names...

**Comment by avive** [comment]
> I think we can do it within one step, which will ask to choose the directory to store the wallet file and set the name. For the directory it also can have a default, the same as we have now.

I think that custom wallet directory is an advanced feature that should only be in the settings and we'll need this wallets-meta-data app data to keep track of these dir for previously opened wallets as long as the netId of each wallet....

**Comment by avive** [comment]
> And since wallet files can be placed in different places in FS, I think that we need to introduce a checkbox in "recover from file" flow, to allow user to choose copy wallet file or not.

Don't we already have this feature as restore from file? The user points to the location of the wallet that smapp doesn't know about and opens that file from that path. It shouldn't copy over that file - it should just use the wallet's FS path as its location...

**Comment by avive** [comment]
> In addition, and just to not forget about it, all the new stuff in a wallet creation flow (like directory and wallet name) should also exist in the "recover from mnemonics" flow.

Recover from mnemonics is designed if you lost the wallet's file or its password. It basically generates a wallet from the seed as the previous wallet. User should go through the flow of local/remote and which api end point to connect to like in a new wallet flow - the only difference is that restore is using the same random seed as the lost wallet and not a new random one...

**Comment by brusherru** [comment]
> I think that custom wallet directory is an advanced feature that should only be in the settings and we'll need this wallets-meta-data app data to keep track of these dir for previously opened wallets as long as the netId of each wallet....

I thought just to store paths to opened/created wallet paths.
When Smapp starts (or shows unlock screen) — it will check for the existence of wallet files by these paths. In case some of them are missing — mark it (aka red text `Wallet file missing (D:\my_wallet....json)` in the dropdown.
So I don't propose to change the default path for wallet files, I propose to store wallets in any place on FS. For example, User can have one in the default location, another one on the desktop, another one on his USB Flash drive...

> Don't we already have this feature as restore from file? The user points to the location of the wallet that smapp doesn't know about and opens that file from that path. It shouldn't copy over that file - it should just use the wallet's FS path as its location...

Nope, right now we're copying it. It sounds no good to me. If I like to store my wallet file on the USB flash drive — it is my choice, don't copy it on FS. Who knows, maybe I had to open Smapp in an internet cafe and don't want to leave traces. That's why I proposed custom paths to wallet files. (But in this case I also may want to avoid storing a path to opened wallet file :D)

And for the same idea, I think that we should provide a possibility for the User to choose a location for his wallet file on creation/importing the wallet file.

**Comment by avive** [comment]
1. I think it is fine to only have path in the wallets data file as you propose.
2. Once we have an option to open a wallet from any path we don't need the restore from file feature anymore :-)
3. I don't think we need to offer option for location to make sure the first session flow is smooth w/o too much information. Users should be able to click to browse their wallet file from the settings... so creation and importing are very different use cases...

**Comment by avive** [comment]
## UI Review Notes

1. Restore command from modal screens such as unlock screen: no need to show additional ‘open’ command. The restore existing wallet first screen can should have 2 commands: 1. Open from file. 2. Restore from 12 words. This screen should be triggered from restore command. Technically, open from file works like restore from file (opens from path) so this is just naming.
2. In settings, the commands under wallets should be: 1. Open wallet (from file). 2. Restore (from 12 words). Open wallet should display the OS dialog to locate the wallet to open.
3. When displaying the wallets drop down in the unlock screen, please remove the parentheses ‘(’ and ‘)’ - no need from them in the sub-title of each drop-down item…. In addition, the date-time can be formatted a little nicer - in a more non-geek-like-us way…. e.g Tuesday, March 3rd, 16:50pm
5. The default name for the 2nd user-created wallet is not good - it is currently called exactly like the first one, ‘main wallet’. Ideally it should be automatically called ‘Wallet 1’, ‘Wallet 2’ based on Smapp knowledge of existing wallet names, so the names are semi-unique and user can always rename a wallet from settings….
6. In settings, add a new row with a command to browse wallet file location. Title: Wallet file. Above the title info: path to wallet file in os. Button: 'Open wallet file directory'.
