### ISSUE TITLE
Release 0.2 Design Review (WIP)

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#740]
## Core 
- [x] Support opening existing wallet. 

## General / All Screens
- [x] All explorer buttons should open explorer in web browser app when clicked. e.g. explorer button next to account name in wallet screen.
- [x] Missing this visual item from the top-right-side of some screens. It appears in the wallet screen:

<img width="103" alt="Screen Shot 2021-06-30 at 9 12 52 AM" src="https://user-images.githubusercontent.com/96002/123910607-6007d000-d983-11eb-966f-229f27c0eaa7.png">

- [x] Use network friendly name in welcome screen from discovery service and not hardcoded `TweedleDee Testnet 0.1.0`. I see the hard-coded value in the network screen and in the welcome screen.

- [ ] All screens which include a text input, such as provide new password or enter wallet password should set input focus to the first text box so user doesn't have to click on it in order to enter text. Some screens have this feature, some don't. For example, set wallet password doesn't but login with password does. Another example - send transaction screen - input focus should go to To input field.

- [x] The right-side stripe changes when user navigates between screens with min window size. It should stay consistent.

![Screen Shot 2021-07-06 at 1 38 26 PM](https://user-images.githubusercontent.com/96002/124587014-d3b44c00-de5f-11eb-921a-fc6d32d1d2fa.png)

![Screen Shot 2021-07-06 at 1 38 19 PM](https://user-images.githubusercontent.com/96002/124587025-d747d300-de5f-11eb-9403-a11fce0dfe55.png)

- [x] Sync status display is inconsistent. In my Smapp, sync status is green in network screen but orange in top header and wallet screen says: 'syncing'. Sync status should be consistent across all sync display elements.

----

## Network Screen
- [x] Handle the case where node process exists (returns status code !=0 to smapp parent process) in the network screen. display generic node crashes error + restart node button + restart node when clicked. 
- [x] Handle all errors from ErrorStream properly - display error message and restart node button in network screen. Restart node when clicked.
- [x] Display friendly network name in network screen subtitle - should come from discovery service friendly network name. (value of `netName` json key). Currently hard-coded to `TwiddleDee 0.1.0`.

----

## Dash Screen
- The dash bottom is cropped when the main window is at its min size and it is not possible to scroll down to see the hidden area - it is cropped.

Dash screen with window at min size:

![Screen Shot 2021-07-06 at 1 35 41 PM](https://user-images.githubusercontent.com/96002/124586430-175a8600-de5f-11eb-8815-d6b9a2e58825.png)

Scrolled all the way down - bottom is cropped:
 
![Screen Shot 2021-07-06 at 1 37 19 PM](https://user-images.githubusercontent.com/96002/124586599-4e309c00-de5f-11eb-8430-3637750d3790.png)

---

## Wallet Screen
- [x] Remove `VAULT` link from main ui (above balance).

**Comment by avive** [comment]
@IlyaVi - added minor ui tweaks as I review the latest smapp in develop.

**Comment by avive** [comment]
Removed this epic from sprints milestones. Individual issues for work in sprints should be created from it.

**Comment by avive** [comment]
This epic is open for reference but all open issues have their own task issues.

**Comment by avive** [comment]
Closing this - all but one issue has been fixed and there's another issue for the remaining open one.
