### ISSUE TITLE
Modern Skin

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#889]
### Rationale

We'd like the default Smapp skin to look and feel consistent with the visual design of https://spacemesh.io

### Acceptance criteria

Provide some steps that an end-user would be able to perform when the feature could be considered as implemented. E.g.:

- [ ] Default smapp skin for new users is modern.
- [ ] User can switch to the legacy dark and lite skins via settings. 
- [ ] Smapp uses the default skin or the user selected skin after restart.

### How to implement

Check [Figma](https://www.figma.com/file/6bbFkIAzVu36bIpUNnMqoy/Smapp-Designs?node-id=8471%3A37718) for the modern skin style guide.

### How to test

Confirm that all screens and UI element are properly rendered in all screens per the UI style guide.

How can we test what’s implemented?

**Comment by maparr** [comment]
Hi @avive , @oriya . I finished with the design changes and right now PR on the review #908 , and just tested the implementation for default skin, we have 2 variants 
1. Client didn't set up our app yet and computer and didn't recover yet from the file or so. The default will be Modern ( new one )
2. Client selected the account on the unlock screen and didn't select the theme yet. The default will be dark/light-based on OS settings 

Can we simplify this step and if not selected, the default will be Modern, for a few reasons. 
1. I unlocked the wallet and typed the password and didn't set up the theme yet, I will get dark/light and won't know about the new theme 
2. I run the app on the new computer and search my file or password to recover the account, I will see Modern skin but after recover will be seeing the light/dark skin 
Shortly we don't have UX to help our clients know what themes we have.  I prefer if the client didn't set up the theme, the default will be Modern and that's it

**Comment by oriya** [comment]
Sounds good to me.
However and/or in addition, I have a question here... why have a legacy dark skin at all? 
my concern is this - having 2 similar dark skins available - can confuse the user - making them not understand why there are so many choices to the same thing - might waste their time and even worst - make them feel like they are "missing something"... (like I am - when looking at this modern skin vs dark-legacy skin).
So my suggestion is no more than dark and light skin - with the default being dark (modern).

**Comment by maparr** [comment]
the design will be different for the light/modern in case we want to delete the dark theme. As an option we can change the light skin to the modern one, I need just need to change the light skin and we will be behaving the light/dark as before, with the option to change it and fix the theme even after 20:00 PM. 
But maybe we want to have an option to change the skin and want to force it to light/dark for Modern skin latter

**Comment by brusherru** [comment]
@maparr I think @oriya means that we need only modern theme, that might be presented as a single one (as website), without "light". But don't rush doing it :)

Since we are keeping og.spacemesh.io for community who like previous website more (and seems we have opened discussions there as well), probably we want to keep it in Smapp as well.
I also agree that it will be better to have a single polished theme and focus on core things instead. But not sure that this is our option, probably all these themes are "beta"-versions (and it will be cool to collect some usage statistics) and we will go into mainnet with the single one. But it is just my assumption. @avive?

**Comment by oriya** [comment]
The current decision is this... leave as-is and rename skins as follows
Modern Dark
Classic Dark
Classic Light

**Comment by oriya** [comment]
In addition, we will be conducting full UX review and get back to you soon.
